/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppMenuRouteImport } from './routes/_app.menu'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app.invoices.index'
import { Route as AppChildrenIndexRouteImport } from './routes/_app.children.index'
import { Route as AppInvoicesIdRouteImport } from './routes/_app.invoices.$id'
import { Route as AppChildrenNewRouteImport } from './routes/_app.children.new'
import { Route as AppChildrenIdRouteImport } from './routes/_app.children.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppChildrenIndexRoute = AppChildrenIndexRouteImport.update({
  id: '/children/',
  path: '/children/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppChildrenNewRoute = AppChildrenNewRouteImport.update({
  id: '/children/new',
  path: '/children/new',
  getParentRoute: () => AppRoute,
} as any)
const AppChildrenIdRoute = AppChildrenIdRouteImport.update({
  id: '/children/$id',
  path: '/children/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/menu': typeof AppMenuRoute
  '/children/$id': typeof AppChildrenIdRoute
  '/children/new': typeof AppChildrenNewRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/children/': typeof AppChildrenIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/menu': typeof AppMenuRoute
  '/': typeof AppIndexRoute
  '/children/$id': typeof AppChildrenIdRoute
  '/children/new': typeof AppChildrenNewRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/children': typeof AppChildrenIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/menu': typeof AppMenuRoute
  '/_app/': typeof AppIndexRoute
  '/_app/children/$id': typeof AppChildrenIdRoute
  '/_app/children/new': typeof AppChildrenNewRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/_app/children/': typeof AppChildrenIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/menu'
    | '/children/$id'
    | '/children/new'
    | '/invoices/$id'
    | '/children/'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/menu'
    | '/'
    | '/children/$id'
    | '/children/new'
    | '/invoices/$id'
    | '/children'
    | '/invoices'
  id:
    | '__root__'
    | '/_app'
    | '/_app/menu'
    | '/_app/'
    | '/_app/children/$id'
    | '/_app/children/new'
    | '/_app/invoices/$id'
    | '/_app/children/'
    | '/_app/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu': {
      id: '/_app/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/children/': {
      id: '/_app/children/'
      path: '/children'
      fullPath: '/children/'
      preLoaderRoute: typeof AppChildrenIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/children/new': {
      id: '/_app/children/new'
      path: '/children/new'
      fullPath: '/children/new'
      preLoaderRoute: typeof AppChildrenNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/children/$id': {
      id: '/_app/children/$id'
      path: '/children/$id'
      fullPath: '/children/$id'
      preLoaderRoute: typeof AppChildrenIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMenuRoute: typeof AppMenuRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChildrenIdRoute: typeof AppChildrenIdRoute
  AppChildrenNewRoute: typeof AppChildrenNewRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppChildrenIndexRoute: typeof AppChildrenIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMenuRoute: AppMenuRoute,
  AppIndexRoute: AppIndexRoute,
  AppChildrenIdRoute: AppChildrenIdRoute,
  AppChildrenNewRoute: AppChildrenNewRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppChildrenIndexRoute: AppChildrenIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
